name: Node.js CI For Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
 run:
  working-directory: ./server

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn test

    - name: Run e2e tests
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn test:e2e